version: "3.8"

networks:
  value-analysis:
    driver: bridge

services:
  mysql:
    container_name: value-analysis-database
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=value-analysis-database
      - MYSQL_PASSWORD=root123
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=root
    ports:
      - "3307:3306"
    networks:
      - value-analysis
    restart: unless-stopped
    volumes:
      - /value-analysis-server_db_data:/var/lib/mysql

  backend:
    env_file: ./.env
    container_name: value-analysis-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - value-analysis
    ports:
      - "5086:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mysql
