// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using value_analysis_server.Api.Database;

#nullable disable

namespace value_analysis_server.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250128011613_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("value_analysis_server.Api.Models.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("justification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("value_analysis_server.Api.Models.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float?>("provider1")
                        .HasColumnType("float");

                    b.Property<float?>("provider2")
                        .HasColumnType("float");

                    b.Property<float?>("provider3")
                        .HasColumnType("float");

                    b.Property<float?>("provider4")
                        .HasColumnType("float");

                    b.Property<float>("quantity")
                        .HasColumnType("float");

                    b.Property<string>("selectedProvider")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = new Guid("f3c4cda2-f5ab-46f3-9b9e-a83939c6a4bb"),
                            code = "001",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3499),
                            description = "Especificação / Descrição do produto genérico 1",
                            name = "Product 1",
                            provider1 = 100f,
                            provider2 = 100f,
                            provider3 = 100f,
                            provider4 = 100f,
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3585)
                        },
                        new
                        {
                            id = new Guid("40ce3dbe-8490-4174-96a5-0b9526c22c33"),
                            code = "002",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3663),
                            description = "Especificação / Descrição do produto genérico 2",
                            name = "Product 2",
                            provider1 = 100f,
                            provider2 = 100f,
                            provider3 = 100f,
                            provider4 = 100f,
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3664)
                        },
                        new
                        {
                            id = new Guid("9bf5b1a2-b749-4012-b7df-63fa67c675c1"),
                            code = "003",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3667),
                            description = "Especificação / Descrição do produto genérico 3",
                            name = "Product 3",
                            provider1 = 100f,
                            provider2 = 100f,
                            provider3 = 100f,
                            provider4 = 100f,
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3668)
                        },
                        new
                        {
                            id = new Guid("8bf1c81b-1d2c-4d0c-9ded-08e0cbb92e78"),
                            code = "004",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3671),
                            description = "Especificação / Descrição do produto genérico 4",
                            name = "Product 4",
                            provider1 = 100f,
                            provider2 = 100f,
                            provider3 = 100f,
                            provider4 = 100f,
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3671)
                        },
                        new
                        {
                            id = new Guid("25f13797-5a4e-47f9-89ae-082090d7a665"),
                            code = "005",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3674),
                            description = "Especificação / Descrição do produto genérico 5",
                            name = "Product 5",
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3674)
                        },
                        new
                        {
                            id = new Guid("358537b8-6340-47d5-bb0e-2572e850eced"),
                            code = "006",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3676),
                            description = "Especificação / Descrição do produto genérico 6",
                            name = "Product 6",
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3676)
                        },
                        new
                        {
                            id = new Guid("24c641c8-fa3b-45fa-bc9f-2bb64262d29c"),
                            code = "007",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3686),
                            description = "Especificação / Descrição do produto genérico 7",
                            name = "Product 7",
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3686)
                        },
                        new
                        {
                            id = new Guid("3286c127-dd88-4301-a82a-dfbe40c5c98a"),
                            code = "008",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3688),
                            description = "Especificação / Descrição do produto genérico 8",
                            name = "Product 8",
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3689)
                        },
                        new
                        {
                            id = new Guid("9b74b628-a3b5-4fad-9335-5c0fbe25ee3c"),
                            code = "009",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3691),
                            description = "Especificação / Descrição do produto genérico 9",
                            name = "Product 9",
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3691)
                        },
                        new
                        {
                            id = new Guid("8d4aa177-dcca-415d-ad4e-20a3b6478ae3"),
                            code = "010",
                            created_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3694),
                            description = "Especificação / Descrição do produto genérico 10",
                            name = "Product 10",
                            quantity = 100f,
                            updated_at = new DateTime(2025, 1, 27, 21, 16, 11, 763, DateTimeKind.Local).AddTicks(3694)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
