// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using value_analysis_server.Api.Database;

#nullable disable

namespace value_analysis_server.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250126180739_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("value_analysis_server.Api.Models.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("justification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("value_analysis_server.Api.Models.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("provider1")
                        .HasColumnType("int");

                    b.Property<int?>("provider2")
                        .HasColumnType("int");

                    b.Property<int?>("provider3")
                        .HasColumnType("int");

                    b.Property<int?>("provider4")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("selectedProvider")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = new Guid("2031301c-e1dc-4ac4-8433-ac4ee5beb342"),
                            code = "001",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1154),
                            description = "Especificação / Descrição do produto genérico 1",
                            name = "Product 1",
                            provider1 = 100,
                            provider2 = 100,
                            provider3 = 100,
                            provider4 = 100,
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1249)
                        },
                        new
                        {
                            id = new Guid("8fb81fa6-0daf-4e3f-8b8a-82f2c69930bc"),
                            code = "002",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1329),
                            description = "Especificação / Descrição do produto genérico 2",
                            name = "Product 2",
                            provider1 = 100,
                            provider2 = 100,
                            provider3 = 100,
                            provider4 = 100,
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1330)
                        },
                        new
                        {
                            id = new Guid("dc035e4d-f889-4961-aa2f-4df046fd6831"),
                            code = "003",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1333),
                            description = "Especificação / Descrição do produto genérico 3",
                            name = "Product 3",
                            provider1 = 100,
                            provider2 = 100,
                            provider3 = 100,
                            provider4 = 100,
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1334)
                        },
                        new
                        {
                            id = new Guid("a55ffbaa-9188-4bc6-86d4-d82464c79170"),
                            code = "004",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1336),
                            description = "Especificação / Descrição do produto genérico 4",
                            name = "Product 4",
                            provider1 = 100,
                            provider2 = 100,
                            provider3 = 100,
                            provider4 = 100,
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1337)
                        },
                        new
                        {
                            id = new Guid("ac2d96f9-afe9-4fa8-b962-9969b09e9d7f"),
                            code = "005",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1339),
                            description = "Especificação / Descrição do produto genérico 5",
                            name = "Product 5",
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1339)
                        },
                        new
                        {
                            id = new Guid("d27386cf-3769-46a6-864a-4229b668bc81"),
                            code = "006",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1350),
                            description = "Especificação / Descrição do produto genérico 6",
                            name = "Product 6",
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1350)
                        },
                        new
                        {
                            id = new Guid("b08d2b45-8f69-4312-9335-ff01b2cf80f4"),
                            code = "007",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1353),
                            description = "Especificação / Descrição do produto genérico 7",
                            name = "Product 7",
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1353)
                        },
                        new
                        {
                            id = new Guid("4b28aa95-eaa0-4e3f-9fe0-8b8c8380cd50"),
                            code = "008",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1355),
                            description = "Especificação / Descrição do produto genérico 8",
                            name = "Product 8",
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1356)
                        },
                        new
                        {
                            id = new Guid("b245d408-dfbd-46d4-b2e2-0cd43357b85d"),
                            code = "009",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1358),
                            description = "Especificação / Descrição do produto genérico 9",
                            name = "Product 9",
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1358)
                        },
                        new
                        {
                            id = new Guid("adfde6a5-c35f-4204-b730-7de18bde1b30"),
                            code = "010",
                            created_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1360),
                            description = "Especificação / Descrição do produto genérico 10",
                            name = "Product 10",
                            quantity = 100,
                            updated_at = new DateTime(2025, 1, 26, 14, 7, 37, 331, DateTimeKind.Local).AddTicks(1361)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
